services:

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD} && sysctl vm.overcommit_memory=1
    env_file:
      - redis/redis.env
    volumes:
      - 'redis_cache:/data'
    networks:
      - config-server_microservice-network

volumes:
  redis_cache:

networks:
  config-server_microservice-network:
    external: true